version: "3.7"
services:
    app:
        build:
            args:
                user: sammy
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: digitalocean.com/php
        container_name: lara_rest_app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - lara_rest

    db:
        image: mysql:5.7
        container_name: lara_rest_db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: lara_rest
            MYSQL_ROOT_PASSWORD: pass
            MYSQL_PASSWORD: lara_rest
            MYSQL_USER: lara_rest
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - ./docker-compose/mysql:/docker-entrypoint-initdb.d
        networks:
            - lara_rest

    webserver:
        image: nginx:alpine
        container_name: lara_rest_nginx
        restart: unless-stopped
        ports:
        - "8050:80"
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d
        networks:
            - lara_rest

networks:
    lara_rest:
        driver: bridge
